language: clojure

jdk:
- openjdk8

services:
- docker
- postgresql

addons:
  postgresql: "9.5"

cache:
  directories:
  - $HOME/.m2

env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: "VNpkJTS8VGm0DIWkuGj4BNzKxuCgK14x9Aa2CDXjI5JoOH6Kp1pb2zGRzEF6rOGwwhx06tNbRo7IQSj/rjS9kJ31/bdP2Y/AjKgZb6ie7fBX73tOy87C/lUQ0iwu2nGNgaaYzPP5EcChs0ZjWkH0CXWiqqyv9lLcBiu9ONjWmfexfGlE7VpI/dNslK8tFRVySK5HE4e99uYzIr7qBphT9/noEqN8ZcJus7wV2oHyzL8gbJVS1AVgiP8M/71ZPLijGNNPC//6yPNi8c1e02P3FbRfx+ZeHFy2GXvVNzS3kONmfEmwP94hQB8582gEQiUhh4F5A0zkzqGZO2XBOhyShH/qaMXcQSw+LiaEvMfsyM94r/Oy6cuwWlvOlYaVb4UW418LCzckE7oZWZuoPGRvG6xpNDgKO+HPJX9/kochOg7ZA4ghG65pqR3MDZnzjCYaJGaqWT9Jm4nxz6w8OLurn53CGQsgfgQlvGl4YneGQxYYDrmJG58y09NOm1zDishQXZ02yAQ1WBtyvCCkEnR0hwyTpCTzRRwf2XKx2ADf71oMvuCMJdI3YR81Wd6JCylYji5KP2H2qWd+2dNwhI0zwte3H9axfkVvLAurZIJihEV1MQ+FsKo09EDUHZv/TCxv+yQ0JG8p84vRKHGpCT2BNtI7AETHR6oSRMQzn8p9v1M="
  # AWS_SECRET_ACCESS_KEY
  - secure: "jDp+bEs6xqXWXQECdspExNXMz4qT2qCp++YWb9uEzpX6H4Timf0CsJGW4LbsI34piggg/DX9BCXD+/ce7byJ94wa3R1pwJVKaLCU1FeFAWJ8sobLcacymVbqzCXCY0gp8T/AAF5rTFX/JZDRgISGQYgqU81ecT6LkCmxLZsZkxt+MTG8tSVnYXXaYIzv6FilsApMJ7T+lavBe85i5DVwC9DPz0zyeAcdi3nApG8+Cshr8YKfW2qU5MHhrNpRLgIY3N0D9FHY+eeFG0yABDqUpWPDUoUeQBDkWFO8Izl7ZXkduZorJKuCwA3Kd9m/hixmY5pwzcEb2GaxCxGVBCoBPZAL2ZlCBqr5klCKYau2wdvnfp/CZ7nwjcHWv+1QotY4yojuv0UfStG7lhSLhIU13mIQZjNE+6V5Q+Z1eQ596Miw12ih9FmTvrgHtqzh95tHUv//wLo+Ls26V/6CqE7Bex1/A/wmM3054YkhU4Meu3wZRcwKXFo50JAJwg8NduYfAoq/bNemIJ4EsUPjon5/X3qhjpfg7Tdt6dqrThU+aWuUA/1HdfXpHbLf5ZHGctAWn51sNnDECiq6ON2BnYPH8xlMLY/B4PMin+6OQ4yGrukYcuGl99ad1ScRveAGLwPUCnbmwKjkdMa5p1nq5VLT4qAc1haSgTjxkHbbaTtjLfc="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh

before_script:
- psql -c "create database valintapiste_test;" -U postgres
- psql -d valintapiste_test -f init_travis_potsgres.sql
- cp -v test.valintapisteservice.travis.edn test.valintapisteservice.edn

script:
- lein test
- lein do clean, uberjar
- mv target/valintapiste-service-*-standalone.jar $DOCKER_BUILD_DIR/artifact/valintapiste-service.jar
- cp -vr oph-configuration $DOCKER_BUILD_DIR/config/

- export BASE_IMAGE="baseimage-fatjar-openjdk8:master"
- ./ci-tools/common/pull-image.sh
- ./ci-tools/build/build-fatjar.sh valintapiste-service

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh valintapiste-service
  on:
    all_branches: true
